aubhona/smart-table

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/docs/api/admin_restaurant.yaml
backend/smart-table/docs/api/admin_user.yaml
backend/smart-table/src/domains/admin/app/services/jwt_service.go
backend/smart-table/src/domains/admin/app/use_cases/place_create_command_handler.go
backend/smart-table/src/domains/admin/app/use_cases/restaurant_create_command_handler.go
backend/smart-table/src/domains/admin/app/use_cases/restaurant_list_command.go
backend/smart-table/src/domains/admin/app/use_cases/restaurant_list_command_handler.go
backend/smart-table/src/domains/admin/di/admin_di.go
backend/smart-table/src/domains/admin/domain/restaurant_repository.go
backend/smart-table/src/domains/admin/infra/pg/mapper/pg_mapper.go
backend/smart-table/src/domains/admin/infra/pg/pg_restaurant_repository.go
backend/smart-table/src/domains/admin/infra/pg/sql/fetch_restuarant_list_by_owner_uuid.sql
backend/smart-table/src/views/admin/v1/restaurant/create_view.go
backend/smart-table/src/views/admin/v1/restaurant/list_view.go
backend/smart-table/tests/admin_place_create_test.go
backend/smart-table/tests/admin_restaurant_create_test.go
backend/smart-table/tests/admin_restaurant_list_test.go

https://tracker.yandex.ru/HSEDEV-15

feat admin: add restaurant list view

---

backend/smart-table/docs/api/admin_restaurant.yaml
backend/smart-table/src/domains/admin/app/queries/s3_query_service.go
backend/smart-table/src/domains/admin/app/use_cases/dish_list_command.go
backend/smart-table/src/domains/admin/app/use_cases/dish_list_command_handler.go
backend/smart-table/src/domains/admin/di/admin_di.go
backend/smart-table/src/domains/customer/app/use_cases/customer_register_command_handler.go
backend/smart-table/src/views/admin/v1/restaurant/dish_list_view.go
backend/smart-table/src/views/bot/on_text_view.go
backend/smart-table/tests/admin_restaurant_dish_create_test.go
backend/smart-table/tests/admin_restaurant_dish_list_test.go

Relates: https://tracker.yandex.ru/HSEDEV-19

feat: add dish list

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/docs/api/admin_user.yaml
backend/smart-table/src/domains/admin/app/use_cases/employee_add_command_handler.go
backend/smart-table/src/domains/admin/app/use_cases/employee_list_command.go
backend/smart-table/src/domains/admin/app/use_cases/employee_list_command_handler.go
backend/smart-table/src/domains/admin/di/admin_di.go
backend/smart-table/src/domains/admin/domain/employee.go
backend/smart-table/src/views/admin/v1/place/employee_list_view.go
backend/smart-table/src/views/admin/v1/place/list_view.go
backend/smart-table/tests/admin_place_employee_add_test.go
backend/smart-table/tests/admin_place_employee_list_test.go

https://tracker.yandex.ru/HSEDEV-21

feat admin: add employee list view

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/postgresql/smart_table/2__admin_create_db.sql
backend/smart-table/src/domains/admin/app/use_cases/dish_list_command_handler.go
backend/smart-table/src/domains/admin/app/use_cases/menu_dish_list_command.go
backend/smart-table/src/domains/admin/app/use_cases/menu_dish_list_command_handler.go
backend/smart-table/src/domains/admin/di/admin_di.go
backend/smart-table/src/views/admin/v1/place/menu_dish_list_view.go
backend/smart-table/tests/admin_place_menu_dish_list_test.go

Relates: https://tracker.yandex.ru/HSEDEV-22

feat HSEDEV-22: add menu dish list

---

backend/smart-table/src/domains/admin/domain/place.go
backend/smart-table/src/domains/customer/app/use_cases/order_create_command_handler.go
backend/smart-table/src/domains/customer/domain/order.go
backend/smart-table/tests/customer_order_create_test.go
backend/smart-table/tests/customer_sign_up_test.go

https://tracker.yandex.ru/HSEDEV-23

first init

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/src/domains/admin/app/services/errors/invalid_table_id.go
backend/smart-table/src/domains/admin/app/services/place_table_service.go
backend/smart-table/src/domains/admin/app/use_cases/table_deeplinks_list_command.go
backend/smart-table/src/domains/admin/app/use_cases/table_deeplinks_list_command_handler.go
backend/smart-table/src/domains/admin/di/admin_di.go
backend/smart-table/src/views/admin/v1/place/table_deeplinks_list_view.go
backend/smart-table/tests/admin_place_table_deeplinks_list_test.go
backend/smart-table/tests/configs/config.yaml

Relates: https://tracker.yandex.ru/HSEDEV-24

feat HSEDEV-24: add deeplinks for QR

---

backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/src/domains/admin/app/services/place_table_service.go
backend/smart-table/src/domains/admin/domain/place.go
backend/smart-table/src/domains/customer/app/use_cases/order_create_command_handler.go
backend/smart-table/src/views/customer/v1/order/create_view.go
backend/smart-table/tests/admin_place_create_test.go
backend/smart-table/tests/customer_order_create_test.go

https://tracker.yandex.ru/HSEDEV-23

feat customer: draft init 2

---

backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/src/domains/admin/infra/pg/pg_place_repository.go
backend/smart-table/src/domains/customer/app/use_cases/errors/customer_already_has_active_order.go
backend/smart-table/src/domains/customer/app/use_cases/order_create_command_handler.go
backend/smart-table/src/domains/customer/domain/order_repository.go
backend/smart-table/src/domains/customer/infra/pg/pg_order_repository.go
backend/smart-table/src/domains/customer/infra/pg/sql/get_active_order_uuid_by_customer_uuid.sql
backend/smart-table/src/views/customer/v1/order/create_view.go

https://tracker.yandex.ru/HSEDEV-23

feat customer: add active order checking

---

backend/smart-table/docs/api/customer.yaml
backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/src/domains/customer/app/use_cases/customer_list_command.go
backend/smart-table/src/domains/customer/app/use_cases/customer_list_command_handler.go
backend/smart-table/src/domains/customer/di/customer_di.go
backend/smart-table/src/utils/optional.go
backend/smart-table/src/views/customer/v1/order/customer_list_view.go

https://tracker.yandex.ru/HSEDEV-26

feat customer: add customer list view

---

backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/src/views/customer/v1/order/cart_view.go
backend/smart-table/src/views/customer/v1/order/catalog_updated_info_view.go
backend/smart-table/src/views/customer/v1/order/finish_view.go
backend/smart-table/src/views/customer/v1/order/items_commit_view.go
backend/smart-table/src/views/customer/v1/order/items_delete_view.go
backend/smart-table/src/views/customer/v1/order/items_draft_view.go
backend/smart-table/src/views/customer/v1/order/tip_save_view.go

Relates: https://tracker.yandex.ru/HSEDEV-28

feat HSEDEV-28: add open api specs

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/docs/internal/item.yaml
backend/smart-table/src/views/admin/v1/place/order_info_view.go
backend/smart-table/src/views/customer/v1/order/customer_list_view.go

https://tracker.yandex.ru/HSEDEV-27

feat admin: add order info speca

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/src/views/admin/v1/place/order_edit_view.go

https://tracker.yandex.ru/HSEDEV-27

feat admin: add order edit speca

---

backend/smart-table/src/domains/customer/app/use_cases/cart_items_count_edit_command_handler.go
backend/smart-table/src/domains/customer/domain/order.go
backend/smart-table/src/domains/customer/infra/pg/pg_order_repository.go
backend/smart-table/src/domains/customer/infra/pg/sql/delete_items.sql
backend/smart-table/src/domains/customer/infra/queries/monolithe_smart_table_query_service.go
backend/smart-table/src/views/customer/v1/order/items_draft_count_edit_view.go
backend/smart-table/tests/customer_order_items_draft_count_edit_test.go

Relates: https://tracker.yandex.ru/HSEDEV-29

feat HSEDEV-29: add tests

---

backend/smart-table/src/domains/customer/app/use_cases/items_commit_command.go
backend/smart-table/src/domains/customer/app/use_cases/items_commit_command_handler.go
backend/smart-table/src/domains/customer/di/customer_di.go
backend/smart-table/src/domains/customer/domain/order.go
backend/smart-table/src/views/customer/v1/order/items_commit_view.go
backend/smart-table/tests/customer_order_items_commit_test.go

Relates: https://tracker.yandex.ru/HSEDEV-34

feat HSEDEV-34: add items commit logic

---

backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/src/domains/customer/app/use_cases/catalog_command_handler.go
backend/smart-table/src/domains/customer/app/use_cases/finish_order_command.go
backend/smart-table/src/domains/customer/app/use_cases/finish_order_command_handler.go
backend/smart-table/src/domains/customer/di/customer_di.go
backend/smart-table/src/domains/customer/domain/order.go
backend/smart-table/src/views/customer/v1/order/catalog_view.go
backend/smart-table/src/views/customer/v1/order/finish_view.go
backend/smart-table/src/views/customer/v1/order/items_commit_view.go
backend/smart-table/tests/configs/config.yaml
backend/smart-table/tests/customer_order_catalog_test.go
backend/smart-table/tests/customer_order_finish_test.go

Relates: https://tracker.yandex.ru/HSEDEV-35

feat HSEDEV-35: add finish order

---

backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/src/domains/customer/app/queries/bot_query_service.go
backend/smart-table/src/domains/customer/app/services/room_code_service.go
backend/smart-table/src/domains/customer/app/services/tip_service.go
backend/smart-table/src/domains/customer/app/use_cases/catalog_command_handler.go
backend/smart-table/src/domains/customer/app/use_cases/save_tip_command.go
backend/smart-table/src/domains/customer/app/use_cases/save_tip_command_handler.go
backend/smart-table/src/domains/customer/di/customer_di.go
backend/smart-table/src/servers/bot.go
backend/smart-table/src/utils/markdown.go
backend/smart-table/src/views/customer/v1/order/catalog_view.go
backend/smart-table/src/views/customer/v1/order/tip_save_view.go
backend/smart-table/tests/customer_order_tip_save_test.go

Relates: https://tracker.yandex.ru/HSEDEV-36

feat HSEDEV-36: add tip save logic

---

backend/smart-table/src/domains/admin/di/admin_di.go
backend/smart-table/src/domains/customer/infra/pg/sql/get_order_uuids_by_place_uuid.sql
backend/smart-table/tests/admin_order_info_test.go
backend/smart-table/tests/admin_order_list_test.go

https://tracker.yandex.ru/HSEDEV-37
https://tracker.yandex.ru/HSEDEV-39

feat admin: add tests to order list and info views

---

backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/src/domains/customer/app/use_cases/cart_command_handler.go
backend/smart-table/src/domains/customer/app/use_cases/item_state_command.go
backend/smart-table/src/domains/customer/app/use_cases/item_state_command_handler.go
backend/smart-table/src/domains/customer/di/customer_di.go
backend/smart-table/src/views/customer/v1/order/cart_view.go
backend/smart-table/src/views/customer/v1/order/item_state_view.go
backend/smart-table/tests/customer_order_item_state_test.go

Relates: https://tracker.yandex.ru/HSEDEV-33

feat HSEDEV-33: add item state

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/docs/internal/customer_dto.yaml
backend/smart-table/src/domains/admin/app/queries/errors/draft_item_status_change_not_allowed.go
backend/smart-table/src/domains/admin/app/queries/errors/incorrect_edit_order_request.go
backend/smart-table/src/domains/admin/app/queries/errors/invalid_item_status.go
backend/smart-table/src/domains/admin/app/queries/errors/invalid_order_status.go
backend/smart-table/src/domains/admin/app/queries/errors/item_status_change_requires_order_status_update.go
backend/smart-table/src/domains/admin/app/queries/errors/order_not_found.go
backend/smart-table/src/domains/admin/app/queries/errors/unsuccess_order_edit.go
backend/smart-table/src/domains/admin/app/queries/smart_table_customer_query_service.go
backend/smart-table/src/domains/admin/app/services/place_table_service.go
backend/smart-table/src/domains/admin/app/use_cases/order_edit_command.go
backend/smart-table/src/domains/admin/app/use_cases/order_edit_command_handler.go
backend/smart-table/src/domains/admin/di/admin_di.go
backend/smart-table/src/domains/admin/infra/queries/monolithe_smart_table_query_service.go
backend/smart-table/src/domains/customer/app/use_cases/errors/incorrect_edit_order_request.go
backend/smart-table/src/domains/customer/app/use_cases/errors/incorrect_table_id.go
backend/smart-table/src/domains/customer/app/use_cases/errors/invalid_table_id.go
backend/smart-table/src/domains/customer/app/use_cases/place_order_edit_command.go
backend/smart-table/src/domains/customer/app/use_cases/place_order_edit_command_handler.go
backend/smart-table/src/domains/customer/di/customer_di.go
backend/smart-table/src/domains/customer/domain/errors/draft_item_status_change_not_allowed.go
backend/smart-table/src/domains/customer/domain/errors/invalid_item_status.go
backend/smart-table/src/domains/customer/domain/errors/invalid_order_status.go
backend/smart-table/src/domains/customer/domain/errors/item_status_change_requires_order_status_update.go
backend/smart-table/src/domains/customer/domain/item.go
backend/smart-table/src/domains/customer/domain/order.go
backend/smart-table/src/views/admin/v1/place/order_edit_view.go
backend/smart-table/src/views/admin/v1/place/order_info_view.go
backend/smart-table/tests/admin_order_info_test.go

https://tracker.yandex.ru/HSEDEV-40

feat admin: add order edit view

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/docs/internal/item.yaml
backend/smart-table/docs/internal/order.yaml
backend/smart-table/src/domains/customer/domain/item.go
backend/smart-table/src/domains/customer/domain/order.go
backend/smart-table/tests/admin_order_edit_test.go

https://tracker.yandex.ru/HSEDEV-40

feat admin: add order edit test

---

backend/smart-table/postgresql/smart_table/3__create_indexes_customer_db.sql
backend/smart-table/postgresql/smart_table/4__create_indexes_admin_db.sql
backend/smart-table/src/domains/admin/app/queries/smart_table_customer_query_service.go
backend/smart-table/src/domains/admin/app/use_cases/order_edit_command.go
backend/smart-table/src/domains/admin/app/use_cases/order_edit_command_handler.go
backend/smart-table/src/domains/admin/infra/pg/sql/fetch_places_by_uuid.sql
backend/smart-table/src/domains/admin/infra/pg/sql/fetch_places_by_uuid_for_update.sql
backend/smart-table/src/domains/admin/infra/pg/sql/fetch_restaurants_by_uuid.sql
backend/smart-table/src/domains/admin/infra/pg/sql/fetch_restaurants_by_uuid_for_update.sql
backend/smart-table/src/domains/admin/infra/queries/monolithe_smart_table_query_service.go
backend/smart-table/src/domains/customer/app/use_cases/cart_command_handler.go
backend/smart-table/src/domains/customer/app/use_cases/catalog_command_handler.go
backend/smart-table/src/domains/customer/app/use_cases/place_order_edit_command.go
backend/smart-table/src/domains/customer/app/use_cases/place_order_edit_command_handler.go
backend/smart-table/src/domains/customer/infra/pg/sql/fetch_orders_by_uuid.sql
backend/smart-table/src/domains/customer/infra/pg/sql/fetch_orders_by_uuid_for_update.sql
backend/smart-table/src/views/admin/v1/place/order_edit_view.go

feat: add indexes, add speed

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/docs/api/customer_order.yaml
backend/smart-table/docs/internal/order.yaml
backend/smart-table/src/domains/admin/app/use_cases/menu_dish_list_command.go
backend/smart-table/src/domains/admin/app/use_cases/menu_dish_list_command_handler.go
backend/smart-table/src/domains/customer/app/queries/smart_table_admin_query_service.go
backend/smart-table/src/domains/customer/app/use_cases/cart_command.go
backend/smart-table/src/domains/customer/app/use_cases/cart_command_handler.go
backend/smart-table/src/domains/customer/app/use_cases/catalog_command.go
backend/smart-table/src/domains/customer/app/use_cases/catalog_command_handler.go
backend/smart-table/src/domains/customer/domain/order.go
backend/smart-table/src/domains/customer/infra/queries/monolithe_smart_table_query_service.go
backend/smart-table/src/views/customer/v1/order/cart_info_view.go
backend/smart-table/src/views/customer/v1/order/cart_view.go
backend/smart-table/src/views/customer/v1/order/catalog_info_view.go
backend/smart-table/src/views/customer/v1/order/catalog_view.go
backend/smart-table/tests/configs/config.yaml
backend/smart-table/tests/customer_order_cart_info_test.go
backend/smart-table/tests/customer_order_catalog_info_test.go

feat: add handlers without picture

---

backend/smart-table/docs/api/admin_place.yaml
backend/smart-table/src/domains/admin/app/queries/errors/draft_item_status_change_not_allowed.go
backend/smart-table/src/domains/admin/app/queries/errors/invalid_item_resolution.go
backend/smart-table/src/domains/admin/app/queries/errors/item_status_change_requires_order_status_update.go
backend/smart-table/src/domains/admin/app/use_cases/menu_dish_delete_command.go
backend/smart-table/src/domains/admin/app/use_cases/menu_dish_delete_command_handler.go
backend/smart-table/src/domains/admin/di/admin_di.go
backend/smart-table/src/domains/admin/domain/place.go
backend/smart-table/src/domains/admin/infra/pg/pg_place_repository.go
backend/smart-table/src/domains/admin/infra/pg/sql/delete_menu_dishes_by_uuid.sql
backend/smart-table/src/domains/admin/infra/queries/monolithe_smart_table_query_service.go
backend/smart-table/src/domains/customer/domain/errors/invalid_item_resolution.go
backend/smart-table/src/domains/customer/domain/item.go
backend/smart-table/src/views/admin/v1/place/menu_dish_delete_view.go
backend/smart-table/src/views/admin/v1/place/order_edit_view.go
backend/smart-table/tests/admin_place_menu_dish_delete_test.go

https://tracker.yandex.ru/HSEDEV-43

feat admin: add delete menu_dish view
